# Generated by Django 5.0.1 on 2024-05-03 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_utility', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='categoryName',
        ),
        migrations.AddField(
            model_name='service',
            name='details',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='service',
            name='file',
            field=models.FileField(default='', upload_to='create_service'),
        ),
        migrations.AddField(
            model_name='service',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='gas_utility.category'),
        ),
    ]
