# Generated by Django 5.0.1 on 2024-05-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_utility', '0003_category_remove_service_categoryname_service_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='create_service'),
        ),
    ]
